                                                                                                                                       
FROM python:3.9-slim

WORKDIR /app

COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variables
ENV AWS_DEFAULT_REGION=ap-south-1
ENV AWS_ACCESS_KEY_ID=AKI++#OHC##XC6MA
ENV AWS_SECRET_ACCESS_KEY=Urn###$$$$gn9K1rI1vm7D1J7d

# Command to run the Python script
CMD ["python", "script.py"]
